# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Midterm_StockPrice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Midterm_StockPrice
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire'
  pod "PromiseKit", "~> 6.8"


end
